services:
  postgres:
    image: postgres:18.1
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-teste123A!}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
