services:
  rabbitmq:
    image: rabbitmq:4.3.0-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test:
        [
          "CMD",
          "rabbitmq-diagnostics",
          "ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped